development:
  adapter: postgresql
  encoding: unicode
  database: aminoize_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: aminoize_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: aminoize_production
  pool: 5
  password:
